version: '3.8'
services:
  application-usuario:
    container_name: application-usuario
    image: application-usuario:latest
    networks:
      - nova-rede
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    expose:
      - 8080

  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - nova-rede

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - nova-rede

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - nova-rede

volumes:
  mongodata:
  prometheus_data: {}
  grafana_data: {}

networks:
  nova-rede:
    driver: bridge