spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/usuarios

  application:
    name: Observability api

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    export:
      prometheus:
        enabled: true

  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

  management:
    metrics:
      tags:
        application=${spring:application:name}